# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/oliver/Git/ch2d

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/oliver/Git/ch2d

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/oliver/Git/ch2d/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/oliver/Git/ch2d/CMakeFiles /home/oliver/Git/ch2d/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/oliver/Git/ch2d/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ch2d

# Build rule for target.
ch2d: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ch2d
.PHONY : ch2d

# fast build rule for target.
ch2d/fast:
	$(MAKE) -f CMakeFiles/ch2d.dir/build.make CMakeFiles/ch2d.dir/build
.PHONY : ch2d/fast

src/ch2d/System.o: src/ch2d/System.cpp.o
.PHONY : src/ch2d/System.o

# target to build an object file
src/ch2d/System.cpp.o:
	$(MAKE) -f CMakeFiles/ch2d.dir/build.make CMakeFiles/ch2d.dir/src/ch2d/System.cpp.o
.PHONY : src/ch2d/System.cpp.o

src/ch2d/System.i: src/ch2d/System.cpp.i
.PHONY : src/ch2d/System.i

# target to preprocess a source file
src/ch2d/System.cpp.i:
	$(MAKE) -f CMakeFiles/ch2d.dir/build.make CMakeFiles/ch2d.dir/src/ch2d/System.cpp.i
.PHONY : src/ch2d/System.cpp.i

src/ch2d/System.s: src/ch2d/System.cpp.s
.PHONY : src/ch2d/System.s

# target to generate assembly for a file
src/ch2d/System.cpp.s:
	$(MAKE) -f CMakeFiles/ch2d.dir/build.make CMakeFiles/ch2d.dir/src/ch2d/System.cpp.s
.PHONY : src/ch2d/System.cpp.s

src/ch2d/bindings/keyboard.o: src/ch2d/bindings/keyboard.cpp.o
.PHONY : src/ch2d/bindings/keyboard.o

# target to build an object file
src/ch2d/bindings/keyboard.cpp.o:
	$(MAKE) -f CMakeFiles/ch2d.dir/build.make CMakeFiles/ch2d.dir/src/ch2d/bindings/keyboard.cpp.o
.PHONY : src/ch2d/bindings/keyboard.cpp.o

src/ch2d/bindings/keyboard.i: src/ch2d/bindings/keyboard.cpp.i
.PHONY : src/ch2d/bindings/keyboard.i

# target to preprocess a source file
src/ch2d/bindings/keyboard.cpp.i:
	$(MAKE) -f CMakeFiles/ch2d.dir/build.make CMakeFiles/ch2d.dir/src/ch2d/bindings/keyboard.cpp.i
.PHONY : src/ch2d/bindings/keyboard.cpp.i

src/ch2d/bindings/keyboard.s: src/ch2d/bindings/keyboard.cpp.s
.PHONY : src/ch2d/bindings/keyboard.s

# target to generate assembly for a file
src/ch2d/bindings/keyboard.cpp.s:
	$(MAKE) -f CMakeFiles/ch2d.dir/build.make CMakeFiles/ch2d.dir/src/ch2d/bindings/keyboard.cpp.s
.PHONY : src/ch2d/bindings/keyboard.cpp.s

src/ch2d/bindings/mouse.o: src/ch2d/bindings/mouse.cpp.o
.PHONY : src/ch2d/bindings/mouse.o

# target to build an object file
src/ch2d/bindings/mouse.cpp.o:
	$(MAKE) -f CMakeFiles/ch2d.dir/build.make CMakeFiles/ch2d.dir/src/ch2d/bindings/mouse.cpp.o
.PHONY : src/ch2d/bindings/mouse.cpp.o

src/ch2d/bindings/mouse.i: src/ch2d/bindings/mouse.cpp.i
.PHONY : src/ch2d/bindings/mouse.i

# target to preprocess a source file
src/ch2d/bindings/mouse.cpp.i:
	$(MAKE) -f CMakeFiles/ch2d.dir/build.make CMakeFiles/ch2d.dir/src/ch2d/bindings/mouse.cpp.i
.PHONY : src/ch2d/bindings/mouse.cpp.i

src/ch2d/bindings/mouse.s: src/ch2d/bindings/mouse.cpp.s
.PHONY : src/ch2d/bindings/mouse.s

# target to generate assembly for a file
src/ch2d/bindings/mouse.cpp.s:
	$(MAKE) -f CMakeFiles/ch2d.dir/build.make CMakeFiles/ch2d.dir/src/ch2d/bindings/mouse.cpp.s
.PHONY : src/ch2d/bindings/mouse.cpp.s

src/ch2d/bindings/sprite.o: src/ch2d/bindings/sprite.cpp.o
.PHONY : src/ch2d/bindings/sprite.o

# target to build an object file
src/ch2d/bindings/sprite.cpp.o:
	$(MAKE) -f CMakeFiles/ch2d.dir/build.make CMakeFiles/ch2d.dir/src/ch2d/bindings/sprite.cpp.o
.PHONY : src/ch2d/bindings/sprite.cpp.o

src/ch2d/bindings/sprite.i: src/ch2d/bindings/sprite.cpp.i
.PHONY : src/ch2d/bindings/sprite.i

# target to preprocess a source file
src/ch2d/bindings/sprite.cpp.i:
	$(MAKE) -f CMakeFiles/ch2d.dir/build.make CMakeFiles/ch2d.dir/src/ch2d/bindings/sprite.cpp.i
.PHONY : src/ch2d/bindings/sprite.cpp.i

src/ch2d/bindings/sprite.s: src/ch2d/bindings/sprite.cpp.s
.PHONY : src/ch2d/bindings/sprite.s

# target to generate assembly for a file
src/ch2d/bindings/sprite.cpp.s:
	$(MAKE) -f CMakeFiles/ch2d.dir/build.make CMakeFiles/ch2d.dir/src/ch2d/bindings/sprite.cpp.s
.PHONY : src/ch2d/bindings/sprite.cpp.s

src/ch2d/bindings/system.o: src/ch2d/bindings/system.cpp.o
.PHONY : src/ch2d/bindings/system.o

# target to build an object file
src/ch2d/bindings/system.cpp.o:
	$(MAKE) -f CMakeFiles/ch2d.dir/build.make CMakeFiles/ch2d.dir/src/ch2d/bindings/system.cpp.o
.PHONY : src/ch2d/bindings/system.cpp.o

src/ch2d/bindings/system.i: src/ch2d/bindings/system.cpp.i
.PHONY : src/ch2d/bindings/system.i

# target to preprocess a source file
src/ch2d/bindings/system.cpp.i:
	$(MAKE) -f CMakeFiles/ch2d.dir/build.make CMakeFiles/ch2d.dir/src/ch2d/bindings/system.cpp.i
.PHONY : src/ch2d/bindings/system.cpp.i

src/ch2d/bindings/system.s: src/ch2d/bindings/system.cpp.s
.PHONY : src/ch2d/bindings/system.s

# target to generate assembly for a file
src/ch2d/bindings/system.cpp.s:
	$(MAKE) -f CMakeFiles/ch2d.dir/build.make CMakeFiles/ch2d.dir/src/ch2d/bindings/system.cpp.s
.PHONY : src/ch2d/bindings/system.cpp.s

src/ch2d/bindings/texture.o: src/ch2d/bindings/texture.cpp.o
.PHONY : src/ch2d/bindings/texture.o

# target to build an object file
src/ch2d/bindings/texture.cpp.o:
	$(MAKE) -f CMakeFiles/ch2d.dir/build.make CMakeFiles/ch2d.dir/src/ch2d/bindings/texture.cpp.o
.PHONY : src/ch2d/bindings/texture.cpp.o

src/ch2d/bindings/texture.i: src/ch2d/bindings/texture.cpp.i
.PHONY : src/ch2d/bindings/texture.i

# target to preprocess a source file
src/ch2d/bindings/texture.cpp.i:
	$(MAKE) -f CMakeFiles/ch2d.dir/build.make CMakeFiles/ch2d.dir/src/ch2d/bindings/texture.cpp.i
.PHONY : src/ch2d/bindings/texture.cpp.i

src/ch2d/bindings/texture.s: src/ch2d/bindings/texture.cpp.s
.PHONY : src/ch2d/bindings/texture.s

# target to generate assembly for a file
src/ch2d/bindings/texture.cpp.s:
	$(MAKE) -f CMakeFiles/ch2d.dir/build.make CMakeFiles/ch2d.dir/src/ch2d/bindings/texture.cpp.s
.PHONY : src/ch2d/bindings/texture.cpp.s

src/ch2d/bindings/view.o: src/ch2d/bindings/view.cpp.o
.PHONY : src/ch2d/bindings/view.o

# target to build an object file
src/ch2d/bindings/view.cpp.o:
	$(MAKE) -f CMakeFiles/ch2d.dir/build.make CMakeFiles/ch2d.dir/src/ch2d/bindings/view.cpp.o
.PHONY : src/ch2d/bindings/view.cpp.o

src/ch2d/bindings/view.i: src/ch2d/bindings/view.cpp.i
.PHONY : src/ch2d/bindings/view.i

# target to preprocess a source file
src/ch2d/bindings/view.cpp.i:
	$(MAKE) -f CMakeFiles/ch2d.dir/build.make CMakeFiles/ch2d.dir/src/ch2d/bindings/view.cpp.i
.PHONY : src/ch2d/bindings/view.cpp.i

src/ch2d/bindings/view.s: src/ch2d/bindings/view.cpp.s
.PHONY : src/ch2d/bindings/view.s

# target to generate assembly for a file
src/ch2d/bindings/view.cpp.s:
	$(MAKE) -f CMakeFiles/ch2d.dir/build.make CMakeFiles/ch2d.dir/src/ch2d/bindings/view.cpp.s
.PHONY : src/ch2d/bindings/view.cpp.s

src/ch2d/bindings/window.o: src/ch2d/bindings/window.cpp.o
.PHONY : src/ch2d/bindings/window.o

# target to build an object file
src/ch2d/bindings/window.cpp.o:
	$(MAKE) -f CMakeFiles/ch2d.dir/build.make CMakeFiles/ch2d.dir/src/ch2d/bindings/window.cpp.o
.PHONY : src/ch2d/bindings/window.cpp.o

src/ch2d/bindings/window.i: src/ch2d/bindings/window.cpp.i
.PHONY : src/ch2d/bindings/window.i

# target to preprocess a source file
src/ch2d/bindings/window.cpp.i:
	$(MAKE) -f CMakeFiles/ch2d.dir/build.make CMakeFiles/ch2d.dir/src/ch2d/bindings/window.cpp.i
.PHONY : src/ch2d/bindings/window.cpp.i

src/ch2d/bindings/window.s: src/ch2d/bindings/window.cpp.s
.PHONY : src/ch2d/bindings/window.s

# target to generate assembly for a file
src/ch2d/bindings/window.cpp.s:
	$(MAKE) -f CMakeFiles/ch2d.dir/build.make CMakeFiles/ch2d.dir/src/ch2d/bindings/window.cpp.s
.PHONY : src/ch2d/bindings/window.cpp.s

src/ch2d/ch2d.o: src/ch2d/ch2d.cpp.o
.PHONY : src/ch2d/ch2d.o

# target to build an object file
src/ch2d/ch2d.cpp.o:
	$(MAKE) -f CMakeFiles/ch2d.dir/build.make CMakeFiles/ch2d.dir/src/ch2d/ch2d.cpp.o
.PHONY : src/ch2d/ch2d.cpp.o

src/ch2d/ch2d.i: src/ch2d/ch2d.cpp.i
.PHONY : src/ch2d/ch2d.i

# target to preprocess a source file
src/ch2d/ch2d.cpp.i:
	$(MAKE) -f CMakeFiles/ch2d.dir/build.make CMakeFiles/ch2d.dir/src/ch2d/ch2d.cpp.i
.PHONY : src/ch2d/ch2d.cpp.i

src/ch2d/ch2d.s: src/ch2d/ch2d.cpp.s
.PHONY : src/ch2d/ch2d.s

# target to generate assembly for a file
src/ch2d/ch2d.cpp.s:
	$(MAKE) -f CMakeFiles/ch2d.dir/build.make CMakeFiles/ch2d.dir/src/ch2d/ch2d.cpp.s
.PHONY : src/ch2d/ch2d.cpp.s

src/ch2d/handlers/EventHandler.o: src/ch2d/handlers/EventHandler.cpp.o
.PHONY : src/ch2d/handlers/EventHandler.o

# target to build an object file
src/ch2d/handlers/EventHandler.cpp.o:
	$(MAKE) -f CMakeFiles/ch2d.dir/build.make CMakeFiles/ch2d.dir/src/ch2d/handlers/EventHandler.cpp.o
.PHONY : src/ch2d/handlers/EventHandler.cpp.o

src/ch2d/handlers/EventHandler.i: src/ch2d/handlers/EventHandler.cpp.i
.PHONY : src/ch2d/handlers/EventHandler.i

# target to preprocess a source file
src/ch2d/handlers/EventHandler.cpp.i:
	$(MAKE) -f CMakeFiles/ch2d.dir/build.make CMakeFiles/ch2d.dir/src/ch2d/handlers/EventHandler.cpp.i
.PHONY : src/ch2d/handlers/EventHandler.cpp.i

src/ch2d/handlers/EventHandler.s: src/ch2d/handlers/EventHandler.cpp.s
.PHONY : src/ch2d/handlers/EventHandler.s

# target to generate assembly for a file
src/ch2d/handlers/EventHandler.cpp.s:
	$(MAKE) -f CMakeFiles/ch2d.dir/build.make CMakeFiles/ch2d.dir/src/ch2d/handlers/EventHandler.cpp.s
.PHONY : src/ch2d/handlers/EventHandler.cpp.s

src/ch2d/handlers/SpriteHandler.o: src/ch2d/handlers/SpriteHandler.cpp.o
.PHONY : src/ch2d/handlers/SpriteHandler.o

# target to build an object file
src/ch2d/handlers/SpriteHandler.cpp.o:
	$(MAKE) -f CMakeFiles/ch2d.dir/build.make CMakeFiles/ch2d.dir/src/ch2d/handlers/SpriteHandler.cpp.o
.PHONY : src/ch2d/handlers/SpriteHandler.cpp.o

src/ch2d/handlers/SpriteHandler.i: src/ch2d/handlers/SpriteHandler.cpp.i
.PHONY : src/ch2d/handlers/SpriteHandler.i

# target to preprocess a source file
src/ch2d/handlers/SpriteHandler.cpp.i:
	$(MAKE) -f CMakeFiles/ch2d.dir/build.make CMakeFiles/ch2d.dir/src/ch2d/handlers/SpriteHandler.cpp.i
.PHONY : src/ch2d/handlers/SpriteHandler.cpp.i

src/ch2d/handlers/SpriteHandler.s: src/ch2d/handlers/SpriteHandler.cpp.s
.PHONY : src/ch2d/handlers/SpriteHandler.s

# target to generate assembly for a file
src/ch2d/handlers/SpriteHandler.cpp.s:
	$(MAKE) -f CMakeFiles/ch2d.dir/build.make CMakeFiles/ch2d.dir/src/ch2d/handlers/SpriteHandler.cpp.s
.PHONY : src/ch2d/handlers/SpriteHandler.cpp.s

src/ch2d/handlers/TextureHandler.o: src/ch2d/handlers/TextureHandler.cpp.o
.PHONY : src/ch2d/handlers/TextureHandler.o

# target to build an object file
src/ch2d/handlers/TextureHandler.cpp.o:
	$(MAKE) -f CMakeFiles/ch2d.dir/build.make CMakeFiles/ch2d.dir/src/ch2d/handlers/TextureHandler.cpp.o
.PHONY : src/ch2d/handlers/TextureHandler.cpp.o

src/ch2d/handlers/TextureHandler.i: src/ch2d/handlers/TextureHandler.cpp.i
.PHONY : src/ch2d/handlers/TextureHandler.i

# target to preprocess a source file
src/ch2d/handlers/TextureHandler.cpp.i:
	$(MAKE) -f CMakeFiles/ch2d.dir/build.make CMakeFiles/ch2d.dir/src/ch2d/handlers/TextureHandler.cpp.i
.PHONY : src/ch2d/handlers/TextureHandler.cpp.i

src/ch2d/handlers/TextureHandler.s: src/ch2d/handlers/TextureHandler.cpp.s
.PHONY : src/ch2d/handlers/TextureHandler.s

# target to generate assembly for a file
src/ch2d/handlers/TextureHandler.cpp.s:
	$(MAKE) -f CMakeFiles/ch2d.dir/build.make CMakeFiles/ch2d.dir/src/ch2d/handlers/TextureHandler.cpp.s
.PHONY : src/ch2d/handlers/TextureHandler.cpp.s

src/ch2d/handlers/ViewHandler.o: src/ch2d/handlers/ViewHandler.cpp.o
.PHONY : src/ch2d/handlers/ViewHandler.o

# target to build an object file
src/ch2d/handlers/ViewHandler.cpp.o:
	$(MAKE) -f CMakeFiles/ch2d.dir/build.make CMakeFiles/ch2d.dir/src/ch2d/handlers/ViewHandler.cpp.o
.PHONY : src/ch2d/handlers/ViewHandler.cpp.o

src/ch2d/handlers/ViewHandler.i: src/ch2d/handlers/ViewHandler.cpp.i
.PHONY : src/ch2d/handlers/ViewHandler.i

# target to preprocess a source file
src/ch2d/handlers/ViewHandler.cpp.i:
	$(MAKE) -f CMakeFiles/ch2d.dir/build.make CMakeFiles/ch2d.dir/src/ch2d/handlers/ViewHandler.cpp.i
.PHONY : src/ch2d/handlers/ViewHandler.cpp.i

src/ch2d/handlers/ViewHandler.s: src/ch2d/handlers/ViewHandler.cpp.s
.PHONY : src/ch2d/handlers/ViewHandler.s

# target to generate assembly for a file
src/ch2d/handlers/ViewHandler.cpp.s:
	$(MAKE) -f CMakeFiles/ch2d.dir/build.make CMakeFiles/ch2d.dir/src/ch2d/handlers/ViewHandler.cpp.s
.PHONY : src/ch2d/handlers/ViewHandler.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... install"
	@echo "... ch2d"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... install/local"
	@echo "... src/ch2d/System.o"
	@echo "... src/ch2d/System.i"
	@echo "... src/ch2d/System.s"
	@echo "... src/ch2d/bindings/keyboard.o"
	@echo "... src/ch2d/bindings/keyboard.i"
	@echo "... src/ch2d/bindings/keyboard.s"
	@echo "... src/ch2d/bindings/mouse.o"
	@echo "... src/ch2d/bindings/mouse.i"
	@echo "... src/ch2d/bindings/mouse.s"
	@echo "... src/ch2d/bindings/sprite.o"
	@echo "... src/ch2d/bindings/sprite.i"
	@echo "... src/ch2d/bindings/sprite.s"
	@echo "... src/ch2d/bindings/system.o"
	@echo "... src/ch2d/bindings/system.i"
	@echo "... src/ch2d/bindings/system.s"
	@echo "... src/ch2d/bindings/texture.o"
	@echo "... src/ch2d/bindings/texture.i"
	@echo "... src/ch2d/bindings/texture.s"
	@echo "... src/ch2d/bindings/view.o"
	@echo "... src/ch2d/bindings/view.i"
	@echo "... src/ch2d/bindings/view.s"
	@echo "... src/ch2d/bindings/window.o"
	@echo "... src/ch2d/bindings/window.i"
	@echo "... src/ch2d/bindings/window.s"
	@echo "... src/ch2d/ch2d.o"
	@echo "... src/ch2d/ch2d.i"
	@echo "... src/ch2d/ch2d.s"
	@echo "... src/ch2d/handlers/EventHandler.o"
	@echo "... src/ch2d/handlers/EventHandler.i"
	@echo "... src/ch2d/handlers/EventHandler.s"
	@echo "... src/ch2d/handlers/SpriteHandler.o"
	@echo "... src/ch2d/handlers/SpriteHandler.i"
	@echo "... src/ch2d/handlers/SpriteHandler.s"
	@echo "... src/ch2d/handlers/TextureHandler.o"
	@echo "... src/ch2d/handlers/TextureHandler.i"
	@echo "... src/ch2d/handlers/TextureHandler.s"
	@echo "... src/ch2d/handlers/ViewHandler.o"
	@echo "... src/ch2d/handlers/ViewHandler.i"
	@echo "... src/ch2d/handlers/ViewHandler.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

